##Kaggle Comp
https://www.kaggle.com/c/titanic/details/getting-started-with-python

##Getting started with Python I

In [1]:
import csv as csv 
import numpy as np
import os
os.getcwd()
os.listdir('.')

['.ipynb_checkpoints',
 'Kaggle_ML',
 'kaggle_titanic_competition.ipynb',
 'notebooks',
 'Intro_to_ml_scikit_learn.ipynb',
 'genderbasedmodel.csv',
 'dplyr_equi.ipynb',
 'advanced_machine_learning_scikitlearn.ipynb']

In [2]:
csv_file_object = csv.reader(open('Kaggle_ML/train.csv', 'rb')) 

In [3]:
header = csv_file_object.next()

In [4]:
data=[]                          # Create a variable called 'data'.
for row in csv_file_object:      # Run through each row in the csv file,
    data.append(row)             # adding each row to the data variable
data = np.array(data)

In [5]:
print data

[['1' '0' '3' ..., '7.25' '' 'S']
 ['2' '1' '1' ..., '71.2833' 'C85' 'C']
 ['3' '1' '3' ..., '7.925' '' 'S']
 ..., 
 ['889' '0' '3' ..., '23.45' '' 'S']
 ['890' '1' '1' ..., '30' 'C148' 'C']
 ['891' '0' '3' ..., '7.75' '' 'Q']]


In [6]:
data[0]

array(['1', '0', '3', 'Braund, Mr. Owen Harris', 'male', '22', '1', '0',
       'A/5 21171', '7.25', '', 'S'], 
      dtype='|S82')

In [7]:
#and to see the last row, type  print data[-1]
print data[-1]

['891' '0' '3' 'Dooley, Mr. Patrick' 'male' '32' '0' '0' '370376' '7.75' ''
 'Q']


In [8]:
#convertimos a float de string la columna "Survived"
data[0::,2].astype(np.float)

array([ 3.,  1.,  3.,  1.,  3.,  3.,  1.,  3.,  3.,  2.,  3.,  1.,  3.,
        3.,  3.,  2.,  3.,  2.,  3.,  3.,  2.,  2.,  3.,  1.,  3.,  3.,
        3.,  1.,  3.,  3.,  1.,  1.,  3.,  2.,  1.,  1.,  3.,  3.,  3.,
        3.,  3.,  2.,  3.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        1.,  2.,  1.,  1.,  2.,  3.,  2.,  3.,  3.,  1.,  1.,  3.,  1.,
        3.,  2.,  3.,  3.,  3.,  2.,  3.,  2.,  3.,  3.,  3.,  3.,  3.,
        2.,  3.,  3.,  3.,  3.,  1.,  2.,  3.,  3.,  3.,  1.,  3.,  3.,
        3.,  1.,  3.,  3.,  3.,  1.,  1.,  2.,  2.,  3.,  3.,  1.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,  3.,  3.,  3.,  3.,
        2.,  1.,  3.,  2.,  3.,  2.,  2.,  1.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  2.,  2.,  2.,  1.,  1.,  3.,  1.,  3.,  3.,  3.,
        3.,  2.,  2.,  3.,  3.,  2.,  2.,  2.,  1.,  3.,  3.,  3.,  1.,
        3.,  3.,  3.,  3.,  3.,  2.,  3.,  3.,  3.,  3.,  1.,  3.,  1.,
        3.,  1.,  3.,  3.,  3.,  1.,  3.,  3.,  1.,  2.,  3.,  3

In [9]:
number_passengers = np.size(data[0::,1].astype(np.float))
number_survived = np.sum(data[0::,1].astype(np.float))

In [10]:
proportion_survivors = number_survived / number_passengers
proportion_survivors

0.38383838383838381

In [11]:
women_only_stats = data[0::,4] == "female" # This finds where all 
                                           # the elements in the gender
                                           # column that equals “female”
men_only_stats = data[0::,4] != "female"   # This finds where all the 
                                           # elements do not equal 
                                           # female (i.e. male)

In [12]:
# Using the index from above we select the females and males separately
women_onboard = data[women_only_stats,1].astype(np.float)     
men_onboard = data[men_only_stats,1].astype(np.float)
# Then we finds the proportions of them that survived
proportion_women_survived = \
                       np.sum(women_onboard) / np.size(women_onboard)  
proportion_men_survived = \
                       np.sum(men_onboard) / np.size(men_onboard) 

# and then print it out
print 'Proportion of women who survived is %s' % proportion_women_survived
print 'Proportion of men who survived is %s' % proportion_men_survived

Proportion of women who survived is 0.742038216561
Proportion of men who survived is 0.188908145581


In [13]:
test_file = open('Kaggle_ML/test.csv', 'rb')
test_file_object = csv.reader(test_file)
header = test_file_object.next()

In [14]:
prediction_file = open("genderbasedmodel.csv", "wb")
prediction_file_object = csv.writer(prediction_file)

In [15]:
prediction_file_object.writerow(["PassengerId", "Survived"])
for row in test_file_object:       # For each row in test.csv
    if row[3] == 'female':         # is it a female, if yes then                                       
        prediction_file_object.writerow([row[0],'1'])    # predict 1
    else:                              # or else if male,       
        prediction_file_object.writerow([row[0],'0'])    # predict 0
test_file.close()
prediction_file.close()

##Getting Started with Python II
https://www.kaggle.com/c/titanic/details/getting-started-with-python-ii

In [16]:
#ahorita los datos todavia son numpy arrays
type(data[0::,5]) 

numpy.ndarray

###Pandas DF

In [17]:
import pandas as pd
import numpy as np

# For .read_csv, always use header=0 when you know row 0 is the header row
df = pd.read_csv('Kaggle_ML/train.csv', header=0)

In [18]:
type(df)

pandas.core.frame.DataFrame

In [19]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [20]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)

In [22]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

###Data Munging

In [23]:
#Let's acquire the first 10 rows of the Age column. In pandas this is

df['Age'][0:10]
#OR
df.Age[0:10]

0    22
1    38
2    26
3    35
4    35
5   NaN
6    54
7     2
8    27
9    14
Name: Age, dtype: float64

In [24]:
df.Age.mean()

29.69911764705882

In [25]:
#filter data
df[df.Age > 60]

PassengerId  Survived  Pclass                                       Name  \
33            34         0       2                      Wheadon, Mr. Edward H   
54            55         0       1             Ostby, Mr. Engelhart Cornelius   
96            97         0       1                  Goldschmidt, Mr. George B   
116          117         0       3                       Connors, Mr. Patrick   
170          171         0       1                  Van der hoef, Mr. Wyckoff   
252          253         0       1                  Stead, Mr. William Thomas   
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
280          281         0       3                           Duane, Mr. Frank   
326          327         0       3                  Nysveen, Mr. Johan Hansen   
438          439         0       1                          Fortune, Mr. Mark   
456          457         0       1                  Millet, Mr. Francis Davis   
483          484         1       3                     Turkula, Mrs. (Hedwig)   
493          494         0       1                    Artagaveytia, Mr. Ramon   
545          546         0       1               Nicholson, Mr. Arthur Ernest   
555          556         0       1                         Wright, Mr. George   
570          571         1       2                         Harris, Mr. George   
625          626         0       1                      Sutton, Mr. Frederick   
630          631         1       1       Barkworth, Mr. Algernon Henry Wilson   
672          673         0       2                Mitchell, Mr. Henry Michael   
745          746         0       1               Crosby, Capt. Edward Gifford   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   
851          852         0       3                        Svensson, Mr. Johan   

        Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked  
33     male  66.0      0      0   C.A. 24579   10.5000          NaN        S  
54     male  65.0      0      1       113509   61.9792          B30        C  
96     male  71.0      0      0     PC 17754   34.6542           A5        C  
116    male  70.5      0      0       370369    7.7500          NaN        Q  
170    male  61.0      0      0       111240   33.5000          B19        S  
252    male  62.0      0      0       113514   26.5500          C87        S  
275  female  63.0      1      0        13502   77.9583           D7        S  
280    male  65.0      0      0       336439    7.7500          NaN        Q  
326    male  61.0      0      0       345364    6.2375          NaN        S  
438    male  64.0      1      4        19950  263.0000  C23 C25 C27        S  
456    male  65.0      0      0        13509   26.5500          E38        S  
483  female  63.0      0      0         4134    9.5875          NaN        S  
493    male  71.0      0      0     PC 17609   49.5042          NaN        C  
545    male  64.0      0      0          693   26.0000          NaN        S  
555    male  62.0      0      0       113807   26.5500          NaN        S  
570    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S  
625    male  61.0      0      0        36963   32.3208          D50        S  
630    male  80.0      0      0        27042   30.0000          A23        S  
672    male  70.0      0      0   C.A. 24580   10.5000          NaN        S  
745    male  70.0      1      1    WE/P 5735   71.0000          B22        S  
829  female  62.0      0      0       113572   80.0000          B28      NaN  
851    male  74.0      0      0       347060    7.7750          NaN        S

In [26]:
#df %>% filter(age >= 60)%>%
#select(Sex, Pclass,Age,Survived)
df[df['Age'] > 70][['Sex', 'Pclass', 'Age', 'Survived']]

#df[df.Age > 45][["Age"]]

Sex  Pclass   Age  Survived
96   male       1  71.0         0
116  male       3  70.5         0
493  male       1  71.0         0
630  male       1  80.0         1
851  male       3  74.0         0

In [27]:
#To filter for missing values, use
df[df['Age'].isnull()][['Sex', 'Pclass', 'Age']]


#df[df.Age.isnull()][["Age","Name"]]

Sex  Pclass  Age
5      male       3  NaN
17     male       2  NaN
19   female       3  NaN
26     male       3  NaN
28   female       3  NaN
29     male       3  NaN
31   female       1  NaN
32   female       3  NaN
36     male       3  NaN
42     male       3  NaN
45     male       3  NaN
46     male       3  NaN
47   female       3  NaN
48     male       3  NaN
55     male       1  NaN
64     male       1  NaN
65     male       3  NaN
76     male       3  NaN
77     male       3  NaN
82   female       3  NaN
87     male       3  NaN
95     male       3  NaN
101    male       3  NaN
107    male       3  NaN
109  female       3  NaN
121    male       3  NaN
126    male       3  NaN
128  female       3  NaN
140  female       3  NaN
154    male       3  NaN
..      ...     ...  ...
718    male       3  NaN
727  female       3  NaN
732    male       2  NaN
738    male       3  NaN
739    male       3  NaN
740    male       1  NaN
760    male       3  NaN
766    male       1  NaN
768    male       3  NaN
773    male       3  NaN
776    male       3  NaN
778    male       3  NaN
783    male       3  NaN
790    male       3  NaN
792  female       3  NaN
793    male       1  NaN
815    male       1  NaN
825    male       3  NaN
826    male       3  NaN
828    male       3  NaN
832    male       3  NaN
837    male       3  NaN
839    male       1  NaN
846    male       3  NaN
849  female       1  NaN
859    male       3  NaN
863  female       3  NaN
868    male       3  NaN
878    male       3  NaN
888  female       3  NaN

[177 rows x 3 columns]

In [28]:
#Here we se ehow many males there were in each class
for i in range(1,4):
    print i, len(df[ (df['Sex'] == 'male') & (df['Pclass'] == i) ])

1 122
2 108
3 347


In [32]:
import pylab as P
#df['Age'].hist()
#P.show()
df['Age'].dropna().hist(bins=16, range=(0,80), alpha = .5)
P.show()

##Cleaning the data
https://www.kaggle.com/c/titanic/details/getting-started-with-python-ii

In [33]:
#make a new columns called gender in which male and female are 0 and 1s
df['Gender'] = df['Sex'].map( {'female': 0, 'male': 1} ).astype(int)

Now we want to deal wih the missing values in the Age column. 

In [34]:
#initialize the empty matrix
median_ages = np.zeros((2,3))
median_ages

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [35]:
#here we get the median ages for each class!
for i in range(0, 2):
    for j in range(0, 3):
        median_ages[i,j] = df[(df['Gender'] == i) & \
                              (df['Pclass'] == j+1)]['Age'].dropna().median()
 
median_ages

array([[ 35. ,  28. ,  21.5],
       [ 40. ,  30. ,  25. ]])

In [36]:
#Make a copy of Age:

df['AgeFill'] = df['Age']

df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked  Gender  AgeFill  
0      0         A/5 21171   7.2500   NaN        S       1       22  
1      0          PC 17599  71.2833   C85        C       0       38  
2      0  STON/O2. 3101282   7.9250   NaN        S       0       26  
3      0            113803  53.1000  C123        S       0       35  
4      0            373450   8.0500   NaN        S       1       35

In [37]:
#fill in the missing into AgeFill
for i in range(0, 2):
    for j in range(0, 3):
        df.loc[ (df.Age.isnull()) & (df.Gender == i) & (df.Pclass == j+1),\
                'AgeFill'] = median_ages[i,j]
        
df[ df['Age'].isnull() ][['Gender','Pclass','Age','AgeFill']].head(10)

Gender  Pclass  Age  AgeFill
5        1       3  NaN     25.0
17       1       2  NaN     30.0
19       0       3  NaN     21.5
26       1       3  NaN     25.0
28       0       3  NaN     21.5
29       1       3  NaN     25.0
31       0       1  NaN     35.0
32       0       3  NaN     21.5
36       1       3  NaN     25.0
42       1       3  NaN     25.0

In [38]:
df['AgeIsNull'] = pd.isnull(df.Age).astype(int)

##Feature Engineering

Let's create a couple of other features, this time using simple math on existing columns. Since we know that Parch is the number of parents or children onboard, and SibSp is the number of siblings or spouses, we could collect those together as a FamilySize:




In [39]:
df['FamilySize'] = df['SibSp'] + df['Parch']

In [41]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked  Gender  AgeFill  \
0      0         A/5 21171   7.2500   NaN        S       1       22   
1      0          PC 17599  71.2833   C85        C       0       38   
2      0  STON/O2. 3101282   7.9250   NaN        S       0       26   
3      0            113803  53.1000  C123        S       0       35   
4      0            373450   8.0500   NaN        S       1       35   

   AgeIsNull  FamilySize  
0          0           1  
1          0           1  
2          0           0  
3          0           1  
4          0           0

In [43]:
df['Age*Class'] = df.AgeFill * df.Pclass
df['Age*Class'].dropna().hist(bins=16, range=(0,80), alpha = .5)
P.show()

##Final Preparation

We have our data almost ready for machine learning. But most basic ML techniques will not work on strings, and in python they almost always require the data to be an array-- the implementations we will see in the sklearn package are not written to use a pandas dataframe. So the last two things we need to do are 

**(1) determine what columns we have left which are not numeric**


**(2) send our pandas.DataFrame back to a numpy.array.**

In [45]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
Gender           int64
AgeFill        float64
AgeIsNull        int64
FamilySize       int64
Age*Class      float64
dtype: object

In [46]:
#which columns are "strings"
df.dtypes[df.dtypes.map(lambda x: x=='object')]


Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [55]:
#drop age since we already copied it to another column
df = df.drop(['Age'], axis=1)

ValueError: labels ['Age'] not contained in axis

In [53]:
#Here we drop any other observations with missing values
df = df.dropna()

But remember that .dropna() removes an observation from df even if it only has 1 NaN, anywhere, in any of its columns. It could delete most of your dataset if you aren't careful with the state of missing values in other columns!

Now we have a clean and tidy dataset that is ready for analysis.

The final step is to convert it into a Numpy array. Pandas can always send back an array using the .values method. Assign to a new variable, train_data:

In [49]:
train_data = df.values
train_data

array([[2, 1, 1, ..., 0, 1, 38.0],
       [4, 1, 1, ..., 0, 1, 35.0],
       [7, 0, 1, ..., 0, 0, 54.0],
       ..., 
       [880, 1, 1, ..., 0, 1, 56.0],
       [888, 1, 1, ..., 0, 0, 19.0],
       [890, 1, 1, ..., 0, 0, 26.0]], dtype=object)

#Getting Started With Random Forests

What is a Random Forest?

As with all the important questions in life, this is best deferred to the Wikipedia page. A random forest is an ensemble of decision trees which will output a prediction value, in this case survival. Each decision tree is constructed by using a random subset of the training data. After you have trained your forest, you can then pass each test row through it, in order to output a prediction. Simple! Well not quite! This particular python function requires floats for the input variables, so all strings need to be converted, and any missing data needs to be filled.

In [71]:
#we have to make sure there are no "strings" or "object"
df.dtypes

Survived        int64
Pclass          int64
SibSp           int64
Parch           int64
Fare          float64
AgeFill       float64
AgeIsNull       int64
FamilySize      int64
Age*Class     float64
dtype: object

In [59]:
df = df.drop(['Name'], axis=1)
df = df.drop(['PassengerId'], axis=1)
df = df.drop(['Cabin'], axis=1)
df = df.drop(['Ticket'], axis=1)
df = df.drop(['Embarked'], axis=1)
train_data = df.values
train_data

array([[1, 1, 'female', ..., 0, 1, 38.0],
       [1, 1, 'female', ..., 0, 1, 35.0],
       [0, 1, 'male', ..., 0, 0, 54.0],
       ..., 
       [1, 1, 'female', ..., 0, 1, 56.0],
       [1, 1, 'female', ..., 0, 0, 19.0],
       [1, 1, 'male', ..., 0, 0, 26.0]], dtype=object)

In [69]:
# Import the random forest package
from sklearn.ensemble import RandomForestClassifier 

# Create the random forest object which will include all the parameters
# for the fit
forest = RandomForestClassifier(n_estimators = 100)

# Fit the training data to the Survived labels and create the decision trees
forest = forest.fit(train_data[0::,1::],train_data[0::,0])

# Take the same decision trees and run it on the test data
#output = forest.predict(test_data)

http://scikit-learn.org/dev/modules/generated/sklearn.ensemble.RandomForestClassifier.html