In [7]:
from sklearn.datasets import make_multilabel_classification
from sklearn.preprocessing import MultiLabelBinarizer
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsRestClassifier

In [146]:
X_train = np.array(["empleos",
                    "numero de unidades economias",
                    "desempleados",
                    "gente de 8 a 9 anios",
                    "gente de 10 a 23 anios",
                    "gente de 23 a 103 anios que tiene empleos",
                    "numero de unidades economicas que fabrican",
                    "producto interno bruto del pais",
                    "produccion total de mineria",
                    "produccion total de plata y oro y bronze",
                    "gente de 103 a 500 anios que no tiene empleos",
                    "poblacion que tiene carencias",
                    "unidades economicas de edicion",
                    "promedio de poblacion que vive en iztapalapa",
                    "esta mujeres, genero, violencia de genero y goles y encuestas",
                    "mujeres y violencia de genero que trabajan en unidades ecnomicas que tiene entre 4 y 105 anios"])

In [147]:
y_train = [[0],[0],[0],[1],[1],[0,1],[0],[0],[0],[0],[0,1],[1],[0],[1],[2],[0,2,1]]

In [148]:
MultiLabelBinarizer().fit_transform(Y)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 0, 1],
       [1, 1, 0, 0, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 1, 1, 0]])

In [165]:
X_test = np.array(['unidades economicas que fabrican celulares',
                   'gente de 45 a 102 anios',
                   'gente de 3 a 75 anios que tiene empleos en sector manufacturero',
                  'adios de 3 a 5768 anios',
                  'gente desempleada que tiene empleos',
                  'alquiler de maquinaria y equipo para construccion, mineria y actividades forestales',
                  'mujeres que reportan violencia de genero que trabajan en unidades economias de entre 4 y 789 anios']) 

In [166]:
target_names = ['economia', 'demografia','violencia de genero']

In [167]:
classifier = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', OneVsRestClassifier(LinearSVC()))])

In [168]:
classifier.fit(X_train, y_train)
predicted = classifier.predict(X_test)
predicted

[(0,), (1,), (0, 1), (1,), (0, 1), (0,), (0, 1, 2)]

In [169]:
for item, labels in zip(X_test, predicted):
    print '%s => %s' % (item, ', '.join(target_names[x] for x in labels))

unidades economicas que fabrican celulares => economia
gente de 45 a 102 anios => demografia
gente de 3 a 75 anios que tiene empleos en sector manufacturero => economia, demografia
adios de 3 a 5768 anios => demografia
gente desempleada que tiene empleos => economia, demografia
alquiler de maquinaria y equipo para construccion, mineria y actividades forestales => economia
mujeres que reportan violencia de genero que trabajan en unidades economias de entre 4 y 789 anios => economia, demografia, violencia de genero


In [155]:
mlb = MultiLabelBinarizer()

In [156]:
mlb

MultiLabelBinarizer(classes=None, sparse_output=False)

In [157]:
 mlb.fit_transform([(1, 2), (3,),(1,3)])

array([[1, 1, 0],
       [0, 0, 1],
       [1, 0, 1]])

In [158]:
mlb.fit_transform([set(['sci-fi', 'thriller']), set(['comedy'])])

array([[0, 1, 1],
       [1, 0, 0]])

In [159]:
list(mlb.classes_)

['comedy', 'sci-fi', 'thriller']